import Vue from 'vue'
import Router from 'vue-router'
import { normalizeURL, decode } from 'ufo'
import { interopDefault } from './utils'
import scrollBehavior from './router.scrollBehavior.js'

const _7a6dbb4c = () => interopDefault(import('~/pages/dashboard/sales/index.vue' /* webpackChunkName: "" */))
const _6f39d8d4 = () => interopDefault(import('..\\pages\\widgets\\index.vue' /* webpackChunkName: "pages/widgets/index" */))
const _85e838ea = () => interopDefault(import('..\\pages\\account\\forgot-password.vue' /* webpackChunkName: "pages/account/forgot-password" */))
const _454ba06f = () => interopDefault(import('..\\pages\\account\\login.vue' /* webpackChunkName: "pages/account/login" */))
const _8bd823e6 = () => interopDefault(import('..\\pages\\account\\register.vue' /* webpackChunkName: "pages/account/register" */))
const _2dd131c2 = () => interopDefault(import('..\\pages\\apps\\calendar\\index.vue' /* webpackChunkName: "pages/apps/calendar/index" */))
const _eafea776 = () => interopDefault(import('..\\pages\\apps\\chat\\index.vue' /* webpackChunkName: "pages/apps/chat/index" */))
const _5272d348 = () => interopDefault(import('..\\pages\\apps\\companies\\index.vue' /* webpackChunkName: "pages/apps/companies/index" */))
const _6ba187a1 = () => interopDefault(import('..\\pages\\apps\\file-manager.vue' /* webpackChunkName: "pages/apps/file-manager" */))
const _7a224910 = () => interopDefault(import('..\\pages\\apps\\tickets\\index.vue' /* webpackChunkName: "pages/apps/tickets/index" */))
const _71583cc2 = () => interopDefault(import('..\\pages\\auth\\confirm-mail.vue' /* webpackChunkName: "pages/auth/confirm-mail" */))
const _3c4ee704 = () => interopDefault(import('..\\pages\\auth\\confirm-mail-2.vue' /* webpackChunkName: "pages/auth/confirm-mail-2" */))
const _8d062bba = () => interopDefault(import('..\\pages\\auth\\lock-screen.vue' /* webpackChunkName: "pages/auth/lock-screen" */))
const _4857de88 = () => interopDefault(import('..\\pages\\auth\\lock-screen-2.vue' /* webpackChunkName: "pages/auth/lock-screen-2" */))
const _0b04767e = () => interopDefault(import('..\\pages\\auth\\login.vue' /* webpackChunkName: "pages/auth/login" */))
const _562dc023 = () => interopDefault(import('..\\pages\\auth\\login-2.vue' /* webpackChunkName: "pages/auth/login-2" */))
const _bac93c76 = () => interopDefault(import('..\\pages\\auth\\logout.vue' /* webpackChunkName: "pages/auth/logout" */))
const _63b6f5aa = () => interopDefault(import('..\\pages\\auth\\logout-2.vue' /* webpackChunkName: "pages/auth/logout-2" */))
const _8766c2d8 = () => interopDefault(import('..\\pages\\auth\\recoverpwd.vue' /* webpackChunkName: "pages/auth/recoverpwd" */))
const _53e78a8e = () => interopDefault(import('..\\pages\\auth\\recoverpwd-2.vue' /* webpackChunkName: "pages/auth/recoverpwd-2" */))
const _4aabacc4 = () => interopDefault(import('..\\pages\\auth\\register.vue' /* webpackChunkName: "pages/auth/register" */))
const _5999a97a = () => interopDefault(import('..\\pages\\auth\\register-2.vue' /* webpackChunkName: "pages/auth/register-2" */))
const _2bfc7eb8 = () => interopDefault(import('..\\pages\\auth\\signin-signup.vue' /* webpackChunkName: "pages/auth/signin-signup" */))
const _1944a1dd = () => interopDefault(import('..\\pages\\auth\\signin-signup-2.vue' /* webpackChunkName: "pages/auth/signin-signup-2" */))
const _dfba5110 = () => interopDefault(import('..\\pages\\charts\\apex\\index.vue' /* webpackChunkName: "pages/charts/apex/index" */))
const _46a3bbaa = () => interopDefault(import('..\\pages\\charts\\c3\\index.vue' /* webpackChunkName: "pages/charts/c3/index" */))
const _127d9a6e = () => interopDefault(import('..\\pages\\charts\\chartist\\index.vue' /* webpackChunkName: "pages/charts/chartist/index" */))
const _6165f9f3 = () => interopDefault(import('..\\pages\\charts\\chartjs\\index.vue' /* webpackChunkName: "pages/charts/chartjs/index" */))
const _d3a1fdc4 = () => interopDefault(import('..\\pages\\charts\\knob.vue' /* webpackChunkName: "pages/charts/knob" */))
const _f85d19f8 = () => interopDefault(import('..\\pages\\contacts\\list.vue' /* webpackChunkName: "pages/contacts/list" */))
const _46b8d39a = () => interopDefault(import('..\\pages\\contacts\\profile.vue' /* webpackChunkName: "pages/contacts/profile" */))
const _0e13c3dd = () => interopDefault(import('..\\pages\\dashboard\\analytics\\index.vue' /* webpackChunkName: "pages/dashboard/analytics/index" */))
const _7e4a5576 = () => interopDefault(import('..\\pages\\dashboard\\crm\\index.vue' /* webpackChunkName: "pages/dashboard/crm/index" */))
const _540d8b17 = () => interopDefault(import('..\\pages\\dashboard\\sales\\index.vue' /* webpackChunkName: "pages/dashboard/sales/index" */))
const _19ef8fc6 = () => interopDefault(import('..\\pages\\ecommerce\\cart.vue' /* webpackChunkName: "pages/ecommerce/cart" */))
const _6705ccc3 = () => interopDefault(import('..\\pages\\ecommerce\\checkout.vue' /* webpackChunkName: "pages/ecommerce/checkout" */))
const _4f0bc34c = () => interopDefault(import('..\\pages\\ecommerce\\customers\\index.vue' /* webpackChunkName: "pages/ecommerce/customers/index" */))
const _0bc61456 = () => interopDefault(import('..\\pages\\ecommerce\\data-products.js' /* webpackChunkName: "pages/ecommerce/data-products" */))
const _cd84f0a6 = () => interopDefault(import('..\\pages\\ecommerce\\order-detail.vue' /* webpackChunkName: "pages/ecommerce/order-detail" */))
const _424b9a20 = () => interopDefault(import('..\\pages\\ecommerce\\orders\\index.vue' /* webpackChunkName: "pages/ecommerce/orders/index" */))
const _6aea9957 = () => interopDefault(import('..\\pages\\ecommerce\\product-create.vue' /* webpackChunkName: "pages/ecommerce/product-create" */))
const _497a9381 = () => interopDefault(import('..\\pages\\ecommerce\\products\\index.vue' /* webpackChunkName: "pages/ecommerce/products/index" */))
const _191c7462 = () => interopDefault(import('..\\pages\\ecommerce\\products-grid.vue' /* webpackChunkName: "pages/ecommerce/products-grid" */))
const _b2924e32 = () => interopDefault(import('..\\pages\\ecommerce\\sellers.vue' /* webpackChunkName: "pages/ecommerce/sellers" */))
const _d5b2245a = () => interopDefault(import('..\\pages\\email\\data-inbox.js' /* webpackChunkName: "pages/email/data-inbox" */))
const _5f6fc2fd = () => interopDefault(import('..\\pages\\email\\inbox.vue' /* webpackChunkName: "pages/email/inbox" */))
const _3a212ef8 = () => interopDefault(import('..\\pages\\email\\sidepanel.vue' /* webpackChunkName: "pages/email/sidepanel" */))
const _5a944ab0 = () => interopDefault(import('..\\pages\\email\\templates.vue' /* webpackChunkName: "pages/email/templates" */))
const _9138249c = () => interopDefault(import('..\\pages\\email\\toolbar.vue' /* webpackChunkName: "pages/email/toolbar" */))
const _2506cd42 = () => interopDefault(import('..\\pages\\extended\\rangeslider.vue' /* webpackChunkName: "pages/extended/rangeslider" */))
const _4e72c733 = () => interopDefault(import('..\\pages\\extended\\scrollspy.vue' /* webpackChunkName: "pages/extended/scrollspy" */))
const _f1ae86ba = () => interopDefault(import('..\\pages\\extended\\sweet-alert.vue' /* webpackChunkName: "pages/extended/sweet-alert" */))
const _bb9d35b8 = () => interopDefault(import('..\\pages\\extended\\tour.vue' /* webpackChunkName: "pages/extended/tour" */))
const _57bbf872 = () => interopDefault(import('..\\pages\\extras\\404.vue' /* webpackChunkName: "pages/extras/404" */))
const _3bde4864 = () => interopDefault(import('..\\pages\\extras\\404-alt.vue' /* webpackChunkName: "pages/extras/404-alt" */))
const _e72c54a2 = () => interopDefault(import('..\\pages\\extras\\500.vue' /* webpackChunkName: "pages/extras/500" */))
const _bfc0cafe = () => interopDefault(import('..\\pages\\extras\\coming-soon.vue' /* webpackChunkName: "pages/extras/coming-soon" */))
const _75926fd3 = () => interopDefault(import('..\\pages\\extras\\faqs.vue' /* webpackChunkName: "pages/extras/faqs" */))
const _77e84ee7 = () => interopDefault(import('..\\pages\\extras\\invoice.vue' /* webpackChunkName: "pages/extras/invoice" */))
const _a748d4aa = () => interopDefault(import('..\\pages\\extras\\lightbox.vue' /* webpackChunkName: "pages/extras/lightbox" */))
const _511c0a66 = () => interopDefault(import('..\\pages\\extras\\maintenance.vue' /* webpackChunkName: "pages/extras/maintenance" */))
const _0828b700 = () => interopDefault(import('..\\pages\\extras\\pricing.vue' /* webpackChunkName: "pages/extras/pricing" */))
const _f69fe5f2 = () => interopDefault(import('..\\pages\\extras\\search-results.vue' /* webpackChunkName: "pages/extras/search-results" */))
const _1cddb46f = () => interopDefault(import('..\\pages\\extras\\sitemap.vue' /* webpackChunkName: "pages/extras/sitemap" */))
const _5a9bcb49 = () => interopDefault(import('..\\pages\\extras\\starter.vue' /* webpackChunkName: "pages/extras/starter" */))
const _1755baf7 = () => interopDefault(import('..\\pages\\extras\\timeline.vue' /* webpackChunkName: "pages/extras/timeline" */))
const _6e893bce = () => interopDefault(import('..\\pages\\forms\\advanced.vue' /* webpackChunkName: "pages/forms/advanced" */))
const _af9fbbba = () => interopDefault(import('..\\pages\\forms\\elements.vue' /* webpackChunkName: "pages/forms/elements" */))
const _20915d26 = () => interopDefault(import('..\\pages\\forms\\file-uploads.vue' /* webpackChunkName: "pages/forms/file-uploads" */))
const _2adee0d0 = () => interopDefault(import('..\\pages\\forms\\mask.vue' /* webpackChunkName: "pages/forms/mask" */))
const _6babb4ee = () => interopDefault(import('..\\pages\\forms\\quill.vue' /* webpackChunkName: "pages/forms/quill" */))
const _3eaa38b6 = () => interopDefault(import('..\\pages\\forms\\validation.vue' /* webpackChunkName: "pages/forms/validation" */))
const _227a7cd2 = () => interopDefault(import('..\\pages\\forms\\wizard.vue' /* webpackChunkName: "pages/forms/wizard" */))
const _c662ddf4 = () => interopDefault(import('..\\pages\\icons\\boxicons.vue' /* webpackChunkName: "pages/icons/boxicons" */))
const _776363b2 = () => interopDefault(import('..\\pages\\icons\\data-fontawesome.js' /* webpackChunkName: "pages/icons/data-fontawesome" */))
const _2b959c0c = () => interopDefault(import('..\\pages\\icons\\data-material.js' /* webpackChunkName: "pages/icons/data-material" */))
const _f2db0a1c = () => interopDefault(import('..\\pages\\icons\\data-remix.js' /* webpackChunkName: "pages/icons/data-remix" */))
const _c0ff27c8 = () => interopDefault(import('..\\pages\\icons\\feather.vue' /* webpackChunkName: "pages/icons/feather" */))
const _a939b988 = () => interopDefault(import('..\\pages\\icons\\font-awesome.vue' /* webpackChunkName: "pages/icons/font-awesome" */))
const _1a13022b = () => interopDefault(import('..\\pages\\icons\\mdi.vue' /* webpackChunkName: "pages/icons/mdi" */))
const _66d58c02 = () => interopDefault(import('..\\pages\\icons\\remix.vue' /* webpackChunkName: "pages/icons/remix" */))
const _fa9f6a26 = () => interopDefault(import('..\\pages\\icons\\weather.vue' /* webpackChunkName: "pages/icons/weather" */))
const _aa9e153a = () => interopDefault(import('..\\pages\\maps\\google.vue' /* webpackChunkName: "pages/maps/google" */))
const _2034b068 = () => interopDefault(import('..\\pages\\tables\\advanced\\index.vue' /* webpackChunkName: "pages/tables/advanced/index" */))
const _4b161ab4 = () => interopDefault(import('..\\pages\\tables\\basic.vue' /* webpackChunkName: "pages/tables/basic" */))
const _24eb1d69 = () => interopDefault(import('..\\pages\\task\\detail.vue' /* webpackChunkName: "pages/task/detail" */))
const _864c075a = () => interopDefault(import('..\\pages\\task\\kanban\\index.vue' /* webpackChunkName: "pages/task/kanban/index" */))
const _23c18736 = () => interopDefault(import('..\\pages\\task\\list.vue' /* webpackChunkName: "pages/task/list" */))
const _18748d3a = () => interopDefault(import('..\\pages\\ui\\avatars.vue' /* webpackChunkName: "pages/ui/avatars" */))
const _7339132a = () => interopDefault(import('..\\pages\\ui\\buttons.vue' /* webpackChunkName: "pages/ui/buttons" */))
const _10b3aa4c = () => interopDefault(import('..\\pages\\ui\\cards.vue' /* webpackChunkName: "pages/ui/cards" */))
const _220166f2 = () => interopDefault(import('..\\pages\\ui\\carousel.vue' /* webpackChunkName: "pages/ui/carousel" */))
const _41ebed2a = () => interopDefault(import('..\\pages\\ui\\dropdowns.vue' /* webpackChunkName: "pages/ui/dropdowns" */))
const _0f6e5111 = () => interopDefault(import('..\\pages\\ui\\general.vue' /* webpackChunkName: "pages/ui/general" */))
const _1c20b2ed = () => interopDefault(import('..\\pages\\ui\\grid.vue' /* webpackChunkName: "pages/ui/grid" */))
const _5735f95f = () => interopDefault(import('..\\pages\\ui\\images.vue' /* webpackChunkName: "pages/ui/images" */))
const _376437f7 = () => interopDefault(import('..\\pages\\ui\\list-group.vue' /* webpackChunkName: "pages/ui/list-group" */))
const _5714ab4d = () => interopDefault(import('..\\pages\\ui\\modals.vue' /* webpackChunkName: "pages/ui/modals" */))
const _dc1aa75e = () => interopDefault(import('..\\pages\\ui\\notifications.vue' /* webpackChunkName: "pages/ui/notifications" */))
const _2953af40 = () => interopDefault(import('..\\pages\\ui\\portlets.vue' /* webpackChunkName: "pages/ui/portlets" */))
const _997f0258 = () => interopDefault(import('..\\pages\\ui\\progress.vue' /* webpackChunkName: "pages/ui/progress" */))
const _d92407f4 = () => interopDefault(import('..\\pages\\ui\\ribbons.vue' /* webpackChunkName: "pages/ui/ribbons" */))
const _5378dfa1 = () => interopDefault(import('..\\pages\\ui\\spinners.vue' /* webpackChunkName: "pages/ui/spinners" */))
const _151bfffa = () => interopDefault(import('..\\pages\\ui\\tabs-accordions.vue' /* webpackChunkName: "pages/ui/tabs-accordions" */))
const _e8035f98 = () => interopDefault(import('..\\pages\\ui\\tooltips-popovers.vue' /* webpackChunkName: "pages/ui/tooltips-popovers" */))
const _1fccf916 = () => interopDefault(import('..\\pages\\ui\\typography.vue' /* webpackChunkName: "pages/ui/typography" */))
const _6db68b64 = () => interopDefault(import('..\\pages\\ui\\video.vue' /* webpackChunkName: "pages/ui/video" */))
const _6906038e = () => interopDefault(import('..\\pages\\widgets\\data.js' /* webpackChunkName: "pages/widgets/data" */))
const _552ad601 = () => interopDefault(import('..\\pages\\apps\\calendar\\data-calendar.js' /* webpackChunkName: "pages/apps/calendar/data-calendar" */))
const _579212b0 = () => interopDefault(import('..\\pages\\apps\\chat\\data.js' /* webpackChunkName: "pages/apps/chat/data" */))
const _6f630b02 = () => interopDefault(import('..\\pages\\apps\\companies\\data.js' /* webpackChunkName: "pages/apps/companies/data" */))
const _3c9f4a33 = () => interopDefault(import('..\\pages\\apps\\tickets\\data.js' /* webpackChunkName: "pages/apps/tickets/data" */))
const _56c0529b = () => interopDefault(import('..\\pages\\charts\\apex\\data.js' /* webpackChunkName: "pages/charts/apex/data" */))
const _af9ec966 = () => interopDefault(import('..\\pages\\charts\\c3\\data.js' /* webpackChunkName: "pages/charts/c3/data" */))
const _2bbb5b11 = () => interopDefault(import('..\\pages\\charts\\chartist\\data.js' /* webpackChunkName: "pages/charts/chartist/data" */))
const _4e2c589a = () => interopDefault(import('..\\pages\\charts\\chartjs\\BarChart.vue' /* webpackChunkName: "pages/charts/chartjs/BarChart" */))
const _76cb36aa = () => interopDefault(import('..\\pages\\charts\\chartjs\\DonutChart.vue' /* webpackChunkName: "pages/charts/chartjs/DonutChart" */))
const _0a82a8cb = () => interopDefault(import('..\\pages\\charts\\chartjs\\LineChart.vue' /* webpackChunkName: "pages/charts/chartjs/LineChart" */))
const _0d63897e = () => interopDefault(import('..\\pages\\charts\\chartjs\\PieChart.vue' /* webpackChunkName: "pages/charts/chartjs/PieChart" */))
const _7da897e2 = () => interopDefault(import('..\\pages\\charts\\chartjs\\PolarChart.vue' /* webpackChunkName: "pages/charts/chartjs/PolarChart" */))
const _3c2fc147 = () => interopDefault(import('..\\pages\\charts\\chartjs\\RadarChart.vue' /* webpackChunkName: "pages/charts/chartjs/RadarChart" */))
const _19827415 = () => interopDefault(import('..\\pages\\dashboard\\analytics\\channels.vue' /* webpackChunkName: "pages/dashboard/analytics/channels" */))
const _790f7d84 = () => interopDefault(import('..\\pages\\dashboard\\analytics\\overview.vue' /* webpackChunkName: "pages/dashboard/analytics/overview" */))
const _30bd4d49 = () => interopDefault(import('..\\pages\\dashboard\\analytics\\social-media.vue' /* webpackChunkName: "pages/dashboard/analytics/social-media" */))
const _79da79fa = () => interopDefault(import('..\\pages\\dashboard\\analytics\\sources.vue' /* webpackChunkName: "pages/dashboard/analytics/sources" */))
const _537d9e13 = () => interopDefault(import('..\\pages\\dashboard\\analytics\\users.vue' /* webpackChunkName: "pages/dashboard/analytics/users" */))
const _cec02c06 = () => interopDefault(import('..\\pages\\ecommerce\\customers\\data.js' /* webpackChunkName: "pages/ecommerce/customers/data" */))
const _93ecc17a = () => interopDefault(import('..\\pages\\ecommerce\\orders\\data.js' /* webpackChunkName: "pages/ecommerce/orders/data" */))
const _2c8d0638 = () => interopDefault(import('..\\pages\\ecommerce\\products\\data.js' /* webpackChunkName: "pages/ecommerce/products/data" */))
const _7e53a78b = () => interopDefault(import('..\\pages\\tables\\advanced\\data.js' /* webpackChunkName: "pages/tables/advanced/data" */))
const _cdbe1b94 = () => interopDefault(import('..\\pages\\task\\kanban\\data.js' /* webpackChunkName: "pages/task/kanban/data" */))
const _3cc62cbe = () => interopDefault(import('..\\pages\\ecommerce\\product-detail\\_id.vue' /* webpackChunkName: "pages/ecommerce/product-detail/_id" */))
const _21bef666 = () => interopDefault(import('..\\pages\\email\\reademail\\_id.vue' /* webpackChunkName: "pages/email/reademail/_id" */))

const emptyFn = () => {}

Vue.use(Router)

export const routerOptions = {
  mode: 'history',
  base: '/',
  linkActiveClass: 'nuxt-link-active',
  linkExactActiveClass: 'nuxt-link-exact-active',
  scrollBehavior,

  routes: [{
    path: "/ar",
    component: _7a6dbb4c
  }, {
    path: "/es",
    component: _7a6dbb4c
  }, {
    path: "/fr",
    component: _7a6dbb4c
  }, {
    path: "/widgets",
    component: _6f39d8d4,
    name: "widgets___en"
  }, {
    path: "/account/forgot-password",
    component: _85e838ea,
    name: "account-forgot-password___en"
  }, {
    path: "/account/login",
    component: _454ba06f,
    name: "account-login___en"
  }, {
    path: "/account/register",
    component: _8bd823e6,
    name: "account-register___en"
  }, {
    path: "/apps/calendar",
    component: _2dd131c2,
    name: "apps-calendar___en"
  }, {
    path: "/apps/chat",
    component: _eafea776,
    name: "apps-chat___en"
  }, {
    path: "/apps/companies",
    component: _5272d348,
    name: "apps-companies___en"
  }, {
    path: "/apps/file-manager",
    component: _6ba187a1,
    name: "apps-file-manager___en"
  }, {
    path: "/apps/tickets",
    component: _7a224910,
    name: "apps-tickets___en"
  }, {
    path: "/ar/widgets",
    component: _6f39d8d4,
    name: "widgets___ar"
  }, {
    path: "/auth/confirm-mail",
    component: _71583cc2,
    name: "auth-confirm-mail___en"
  }, {
    path: "/auth/confirm-mail-2",
    component: _3c4ee704,
    name: "auth-confirm-mail-2___en"
  }, {
    path: "/auth/lock-screen",
    component: _8d062bba,
    name: "auth-lock-screen___en"
  }, {
    path: "/auth/lock-screen-2",
    component: _4857de88,
    name: "auth-lock-screen-2___en"
  }, {
    path: "/auth/login",
    component: _0b04767e,
    name: "auth-login___en"
  }, {
    path: "/auth/login-2",
    component: _562dc023,
    name: "auth-login-2___en"
  }, {
    path: "/auth/logout",
    component: _bac93c76,
    name: "auth-logout___en"
  }, {
    path: "/auth/logout-2",
    component: _63b6f5aa,
    name: "auth-logout-2___en"
  }, {
    path: "/auth/recoverpwd",
    component: _8766c2d8,
    name: "auth-recoverpwd___en"
  }, {
    path: "/auth/recoverpwd-2",
    component: _53e78a8e,
    name: "auth-recoverpwd-2___en"
  }, {
    path: "/auth/register",
    component: _4aabacc4,
    name: "auth-register___en"
  }, {
    path: "/auth/register-2",
    component: _5999a97a,
    name: "auth-register-2___en"
  }, {
    path: "/auth/signin-signup",
    component: _2bfc7eb8,
    name: "auth-signin-signup___en"
  }, {
    path: "/auth/signin-signup-2",
    component: _1944a1dd,
    name: "auth-signin-signup-2___en"
  }, {
    path: "/charts/apex",
    component: _dfba5110,
    name: "charts-apex___en"
  }, {
    path: "/charts/c3",
    component: _46a3bbaa,
    name: "charts-c3___en"
  }, {
    path: "/charts/chartist",
    component: _127d9a6e,
    name: "charts-chartist___en"
  }, {
    path: "/charts/chartjs",
    component: _6165f9f3,
    name: "charts-chartjs___en"
  }, {
    path: "/charts/knob",
    component: _d3a1fdc4,
    name: "charts-knob___en"
  }, {
    path: "/contacts/list",
    component: _f85d19f8,
    name: "contacts-list___en"
  }, {
    path: "/contacts/profile",
    component: _46b8d39a,
    name: "contacts-profile___en"
  }, {
    path: "/dashboard/analytics",
    component: _0e13c3dd,
    name: "dashboard-analytics___en"
  }, {
    path: "/dashboard/crm",
    component: _7e4a5576,
    name: "dashboard-crm___en"
  }, {
    path: "/dashboard/sales",
    component: _540d8b17,
    name: "dashboard-sales___en"
  }, {
    path: "/ecommerce/cart",
    component: _19ef8fc6,
    name: "ecommerce-cart___en"
  }, {
    path: "/ecommerce/checkout",
    component: _6705ccc3,
    name: "ecommerce-checkout___en"
  }, {
    path: "/ecommerce/customers",
    component: _4f0bc34c,
    name: "ecommerce-customers___en"
  }, {
    path: "/ecommerce/data-products",
    component: _0bc61456,
    name: "ecommerce-data-products___en"
  }, {
    path: "/ecommerce/order-detail",
    component: _cd84f0a6,
    name: "ecommerce-order-detail___en"
  }, {
    path: "/ecommerce/orders",
    component: _424b9a20,
    name: "ecommerce-orders___en"
  }, {
    path: "/ecommerce/product-create",
    component: _6aea9957,
    name: "ecommerce-product-create___en"
  }, {
    path: "/ecommerce/products",
    component: _497a9381,
    name: "ecommerce-products___en"
  }, {
    path: "/ecommerce/products-grid",
    component: _191c7462,
    name: "ecommerce-products-grid___en"
  }, {
    path: "/ecommerce/sellers",
    component: _b2924e32,
    name: "ecommerce-sellers___en"
  }, {
    path: "/email/data-inbox",
    component: _d5b2245a,
    name: "email-data-inbox___en"
  }, {
    path: "/email/inbox",
    component: _5f6fc2fd,
    name: "email-inbox___en"
  }, {
    path: "/email/sidepanel",
    component: _3a212ef8,
    name: "email-sidepanel___en"
  }, {
    path: "/email/templates",
    component: _5a944ab0,
    name: "email-templates___en"
  }, {
    path: "/email/toolbar",
    component: _9138249c,
    name: "email-toolbar___en"
  }, {
    path: "/es/widgets",
    component: _6f39d8d4,
    name: "widgets___es"
  }, {
    path: "/extended/rangeslider",
    component: _2506cd42,
    name: "extended-rangeslider___en"
  }, {
    path: "/extended/scrollspy",
    component: _4e72c733,
    name: "extended-scrollspy___en"
  }, {
    path: "/extended/sweet-alert",
    component: _f1ae86ba,
    name: "extended-sweet-alert___en"
  }, {
    path: "/extended/tour",
    component: _bb9d35b8,
    name: "extended-tour___en"
  }, {
    path: "/extras/404",
    component: _57bbf872,
    name: "extras-404___en"
  }, {
    path: "/extras/404-alt",
    component: _3bde4864,
    name: "extras-404-alt___en"
  }, {
    path: "/extras/500",
    component: _e72c54a2,
    name: "extras-500___en"
  }, {
    path: "/extras/coming-soon",
    component: _bfc0cafe,
    name: "extras-coming-soon___en"
  }, {
    path: "/extras/faqs",
    component: _75926fd3,
    name: "extras-faqs___en"
  }, {
    path: "/extras/invoice",
    component: _77e84ee7,
    name: "extras-invoice___en"
  }, {
    path: "/extras/lightbox",
    component: _a748d4aa,
    name: "extras-lightbox___en"
  }, {
    path: "/extras/maintenance",
    component: _511c0a66,
    name: "extras-maintenance___en"
  }, {
    path: "/extras/pricing",
    component: _0828b700,
    name: "extras-pricing___en"
  }, {
    path: "/extras/search-results",
    component: _f69fe5f2,
    name: "extras-search-results___en"
  }, {
    path: "/extras/sitemap",
    component: _1cddb46f,
    name: "extras-sitemap___en"
  }, {
    path: "/extras/starter",
    component: _5a9bcb49,
    name: "extras-starter___en"
  }, {
    path: "/extras/timeline",
    component: _1755baf7,
    name: "extras-timeline___en"
  }, {
    path: "/forms/advanced",
    component: _6e893bce,
    name: "forms-advanced___en"
  }, {
    path: "/forms/elements",
    component: _af9fbbba,
    name: "forms-elements___en"
  }, {
    path: "/forms/file-uploads",
    component: _20915d26,
    name: "forms-file-uploads___en"
  }, {
    path: "/forms/mask",
    component: _2adee0d0,
    name: "forms-mask___en"
  }, {
    path: "/forms/quill",
    component: _6babb4ee,
    name: "forms-quill___en"
  }, {
    path: "/forms/validation",
    component: _3eaa38b6,
    name: "forms-validation___en"
  }, {
    path: "/forms/wizard",
    component: _227a7cd2,
    name: "forms-wizard___en"
  }, {
    path: "/fr/widgets",
    component: _6f39d8d4,
    name: "widgets___fr"
  }, {
    path: "/icons/boxicons",
    component: _c662ddf4,
    name: "icons-boxicons___en"
  }, {
    path: "/icons/data-fontawesome",
    component: _776363b2,
    name: "icons-data-fontawesome___en"
  }, {
    path: "/icons/data-material",
    component: _2b959c0c,
    name: "icons-data-material___en"
  }, {
    path: "/icons/data-remix",
    component: _f2db0a1c,
    name: "icons-data-remix___en"
  }, {
    path: "/icons/feather",
    component: _c0ff27c8,
    name: "icons-feather___en"
  }, {
    path: "/icons/font-awesome",
    component: _a939b988,
    name: "icons-font-awesome___en"
  }, {
    path: "/icons/mdi",
    component: _1a13022b,
    name: "icons-mdi___en"
  }, {
    path: "/icons/remix",
    component: _66d58c02,
    name: "icons-remix___en"
  }, {
    path: "/icons/weather",
    component: _fa9f6a26,
    name: "icons-weather___en"
  }, {
    path: "/maps/google",
    component: _aa9e153a,
    name: "maps-google___en"
  }, {
    path: "/tables/advanced",
    component: _2034b068,
    name: "tables-advanced___en"
  }, {
    path: "/tables/basic",
    component: _4b161ab4,
    name: "tables-basic___en"
  }, {
    path: "/task/detail",
    component: _24eb1d69,
    name: "task-detail___en"
  }, {
    path: "/task/kanban",
    component: _864c075a,
    name: "task-kanban___en"
  }, {
    path: "/task/list",
    component: _23c18736,
    name: "task-list___en"
  }, {
    path: "/ui/avatars",
    component: _18748d3a,
    name: "ui-avatars___en"
  }, {
    path: "/ui/buttons",
    component: _7339132a,
    name: "ui-buttons___en"
  }, {
    path: "/ui/cards",
    component: _10b3aa4c,
    name: "ui-cards___en"
  }, {
    path: "/ui/carousel",
    component: _220166f2,
    name: "ui-carousel___en"
  }, {
    path: "/ui/dropdowns",
    component: _41ebed2a,
    name: "ui-dropdowns___en"
  }, {
    path: "/ui/general",
    component: _0f6e5111,
    name: "ui-general___en"
  }, {
    path: "/ui/grid",
    component: _1c20b2ed,
    name: "ui-grid___en"
  }, {
    path: "/ui/images",
    component: _5735f95f,
    name: "ui-images___en"
  }, {
    path: "/ui/list-group",
    component: _376437f7,
    name: "ui-list-group___en"
  }, {
    path: "/ui/modals",
    component: _5714ab4d,
    name: "ui-modals___en"
  }, {
    path: "/ui/notifications",
    component: _dc1aa75e,
    name: "ui-notifications___en"
  }, {
    path: "/ui/portlets",
    component: _2953af40,
    name: "ui-portlets___en"
  }, {
    path: "/ui/progress",
    component: _997f0258,
    name: "ui-progress___en"
  }, {
    path: "/ui/ribbons",
    component: _d92407f4,
    name: "ui-ribbons___en"
  }, {
    path: "/ui/spinners",
    component: _5378dfa1,
    name: "ui-spinners___en"
  }, {
    path: "/ui/tabs-accordions",
    component: _151bfffa,
    name: "ui-tabs-accordions___en"
  }, {
    path: "/ui/tooltips-popovers",
    component: _e8035f98,
    name: "ui-tooltips-popovers___en"
  }, {
    path: "/ui/typography",
    component: _1fccf916,
    name: "ui-typography___en"
  }, {
    path: "/ui/video",
    component: _6db68b64,
    name: "ui-video___en"
  }, {
    path: "/widgets/data",
    component: _6906038e,
    name: "widgets-data___en"
  }, {
    path: "/apps/calendar/data-calendar",
    component: _552ad601,
    name: "apps-calendar-data-calendar___en"
  }, {
    path: "/apps/chat/data",
    component: _579212b0,
    name: "apps-chat-data___en"
  }, {
    path: "/apps/companies/data",
    component: _6f630b02,
    name: "apps-companies-data___en"
  }, {
    path: "/apps/tickets/data",
    component: _3c9f4a33,
    name: "apps-tickets-data___en"
  }, {
    path: "/ar/account/forgot-password",
    component: _85e838ea,
    name: "account-forgot-password___ar"
  }, {
    path: "/ar/account/login",
    component: _454ba06f,
    name: "account-login___ar"
  }, {
    path: "/ar/account/register",
    component: _8bd823e6,
    name: "account-register___ar"
  }, {
    path: "/ar/apps/calendar",
    component: _2dd131c2,
    name: "apps-calendar___ar"
  }, {
    path: "/ar/apps/chat",
    component: _eafea776,
    name: "apps-chat___ar"
  }, {
    path: "/ar/apps/companies",
    component: _5272d348,
    name: "apps-companies___ar"
  }, {
    path: "/ar/apps/file-manager",
    component: _6ba187a1,
    name: "apps-file-manager___ar"
  }, {
    path: "/ar/apps/tickets",
    component: _7a224910,
    name: "apps-tickets___ar"
  }, {
    path: "/ar/auth/confirm-mail",
    component: _71583cc2,
    name: "auth-confirm-mail___ar"
  }, {
    path: "/ar/auth/confirm-mail-2",
    component: _3c4ee704,
    name: "auth-confirm-mail-2___ar"
  }, {
    path: "/ar/auth/lock-screen",
    component: _8d062bba,
    name: "auth-lock-screen___ar"
  }, {
    path: "/ar/auth/lock-screen-2",
    component: _4857de88,
    name: "auth-lock-screen-2___ar"
  }, {
    path: "/ar/auth/login",
    component: _0b04767e,
    name: "auth-login___ar"
  }, {
    path: "/ar/auth/login-2",
    component: _562dc023,
    name: "auth-login-2___ar"
  }, {
    path: "/ar/auth/logout",
    component: _bac93c76,
    name: "auth-logout___ar"
  }, {
    path: "/ar/auth/logout-2",
    component: _63b6f5aa,
    name: "auth-logout-2___ar"
  }, {
    path: "/ar/auth/recoverpwd",
    component: _8766c2d8,
    name: "auth-recoverpwd___ar"
  }, {
    path: "/ar/auth/recoverpwd-2",
    component: _53e78a8e,
    name: "auth-recoverpwd-2___ar"
  }, {
    path: "/ar/auth/register",
    component: _4aabacc4,
    name: "auth-register___ar"
  }, {
    path: "/ar/auth/register-2",
    component: _5999a97a,
    name: "auth-register-2___ar"
  }, {
    path: "/ar/auth/signin-signup",
    component: _2bfc7eb8,
    name: "auth-signin-signup___ar"
  }, {
    path: "/ar/auth/signin-signup-2",
    component: _1944a1dd,
    name: "auth-signin-signup-2___ar"
  }, {
    path: "/ar/charts/apex",
    component: _dfba5110,
    name: "charts-apex___ar"
  }, {
    path: "/ar/charts/c3",
    component: _46a3bbaa,
    name: "charts-c3___ar"
  }, {
    path: "/ar/charts/chartist",
    component: _127d9a6e,
    name: "charts-chartist___ar"
  }, {
    path: "/ar/charts/chartjs",
    component: _6165f9f3,
    name: "charts-chartjs___ar"
  }, {
    path: "/ar/charts/knob",
    component: _d3a1fdc4,
    name: "charts-knob___ar"
  }, {
    path: "/ar/contacts/list",
    component: _f85d19f8,
    name: "contacts-list___ar"
  }, {
    path: "/ar/contacts/profile",
    component: _46b8d39a,
    name: "contacts-profile___ar"
  }, {
    path: "/ar/dashboard/analytics",
    component: _0e13c3dd,
    name: "dashboard-analytics___ar"
  }, {
    path: "/ar/dashboard/crm",
    component: _7e4a5576,
    name: "dashboard-crm___ar"
  }, {
    path: "/ar/dashboard/sales",
    component: _540d8b17,
    name: "dashboard-sales___ar"
  }, {
    path: "/ar/ecommerce/cart",
    component: _19ef8fc6,
    name: "ecommerce-cart___ar"
  }, {
    path: "/ar/ecommerce/checkout",
    component: _6705ccc3,
    name: "ecommerce-checkout___ar"
  }, {
    path: "/ar/ecommerce/customers",
    component: _4f0bc34c,
    name: "ecommerce-customers___ar"
  }, {
    path: "/ar/ecommerce/data-products",
    component: _0bc61456,
    name: "ecommerce-data-products___ar"
  }, {
    path: "/ar/ecommerce/order-detail",
    component: _cd84f0a6,
    name: "ecommerce-order-detail___ar"
  }, {
    path: "/ar/ecommerce/orders",
    component: _424b9a20,
    name: "ecommerce-orders___ar"
  }, {
    path: "/ar/ecommerce/product-create",
    component: _6aea9957,
    name: "ecommerce-product-create___ar"
  }, {
    path: "/ar/ecommerce/products",
    component: _497a9381,
    name: "ecommerce-products___ar"
  }, {
    path: "/ar/ecommerce/products-grid",
    component: _191c7462,
    name: "ecommerce-products-grid___ar"
  }, {
    path: "/ar/ecommerce/sellers",
    component: _b2924e32,
    name: "ecommerce-sellers___ar"
  }, {
    path: "/ar/email/data-inbox",
    component: _d5b2245a,
    name: "email-data-inbox___ar"
  }, {
    path: "/ar/email/inbox",
    component: _5f6fc2fd,
    name: "email-inbox___ar"
  }, {
    path: "/ar/email/sidepanel",
    component: _3a212ef8,
    name: "email-sidepanel___ar"
  }, {
    path: "/ar/email/templates",
    component: _5a944ab0,
    name: "email-templates___ar"
  }, {
    path: "/ar/email/toolbar",
    component: _9138249c,
    name: "email-toolbar___ar"
  }, {
    path: "/ar/extended/rangeslider",
    component: _2506cd42,
    name: "extended-rangeslider___ar"
  }, {
    path: "/ar/extended/scrollspy",
    component: _4e72c733,
    name: "extended-scrollspy___ar"
  }, {
    path: "/ar/extended/sweet-alert",
    component: _f1ae86ba,
    name: "extended-sweet-alert___ar"
  }, {
    path: "/ar/extended/tour",
    component: _bb9d35b8,
    name: "extended-tour___ar"
  }, {
    path: "/ar/extras/404",
    component: _57bbf872,
    name: "extras-404___ar"
  }, {
    path: "/ar/extras/404-alt",
    component: _3bde4864,
    name: "extras-404-alt___ar"
  }, {
    path: "/ar/extras/500",
    component: _e72c54a2,
    name: "extras-500___ar"
  }, {
    path: "/ar/extras/coming-soon",
    component: _bfc0cafe,
    name: "extras-coming-soon___ar"
  }, {
    path: "/ar/extras/faqs",
    component: _75926fd3,
    name: "extras-faqs___ar"
  }, {
    path: "/ar/extras/invoice",
    component: _77e84ee7,
    name: "extras-invoice___ar"
  }, {
    path: "/ar/extras/lightbox",
    component: _a748d4aa,
    name: "extras-lightbox___ar"
  }, {
    path: "/ar/extras/maintenance",
    component: _511c0a66,
    name: "extras-maintenance___ar"
  }, {
    path: "/ar/extras/pricing",
    component: _0828b700,
    name: "extras-pricing___ar"
  }, {
    path: "/ar/extras/search-results",
    component: _f69fe5f2,
    name: "extras-search-results___ar"
  }, {
    path: "/ar/extras/sitemap",
    component: _1cddb46f,
    name: "extras-sitemap___ar"
  }, {
    path: "/ar/extras/starter",
    component: _5a9bcb49,
    name: "extras-starter___ar"
  }, {
    path: "/ar/extras/timeline",
    component: _1755baf7,
    name: "extras-timeline___ar"
  }, {
    path: "/ar/forms/advanced",
    component: _6e893bce,
    name: "forms-advanced___ar"
  }, {
    path: "/ar/forms/elements",
    component: _af9fbbba,
    name: "forms-elements___ar"
  }, {
    path: "/ar/forms/file-uploads",
    component: _20915d26,
    name: "forms-file-uploads___ar"
  }, {
    path: "/ar/forms/mask",
    component: _2adee0d0,
    name: "forms-mask___ar"
  }, {
    path: "/ar/forms/quill",
    component: _6babb4ee,
    name: "forms-quill___ar"
  }, {
    path: "/ar/forms/validation",
    component: _3eaa38b6,
    name: "forms-validation___ar"
  }, {
    path: "/ar/forms/wizard",
    component: _227a7cd2,
    name: "forms-wizard___ar"
  }, {
    path: "/ar/icons/boxicons",
    component: _c662ddf4,
    name: "icons-boxicons___ar"
  }, {
    path: "/ar/icons/data-fontawesome",
    component: _776363b2,
    name: "icons-data-fontawesome___ar"
  }, {
    path: "/ar/icons/data-material",
    component: _2b959c0c,
    name: "icons-data-material___ar"
  }, {
    path: "/ar/icons/data-remix",
    component: _f2db0a1c,
    name: "icons-data-remix___ar"
  }, {
    path: "/ar/icons/feather",
    component: _c0ff27c8,
    name: "icons-feather___ar"
  }, {
    path: "/ar/icons/font-awesome",
    component: _a939b988,
    name: "icons-font-awesome___ar"
  }, {
    path: "/ar/icons/mdi",
    component: _1a13022b,
    name: "icons-mdi___ar"
  }, {
    path: "/ar/icons/remix",
    component: _66d58c02,
    name: "icons-remix___ar"
  }, {
    path: "/ar/icons/weather",
    component: _fa9f6a26,
    name: "icons-weather___ar"
  }, {
    path: "/ar/maps/google",
    component: _aa9e153a,
    name: "maps-google___ar"
  }, {
    path: "/ar/tables/advanced",
    component: _2034b068,
    name: "tables-advanced___ar"
  }, {
    path: "/ar/tables/basic",
    component: _4b161ab4,
    name: "tables-basic___ar"
  }, {
    path: "/ar/task/detail",
    component: _24eb1d69,
    name: "task-detail___ar"
  }, {
    path: "/ar/task/kanban",
    component: _864c075a,
    name: "task-kanban___ar"
  }, {
    path: "/ar/task/list",
    component: _23c18736,
    name: "task-list___ar"
  }, {
    path: "/ar/ui/avatars",
    component: _18748d3a,
    name: "ui-avatars___ar"
  }, {
    path: "/ar/ui/buttons",
    component: _7339132a,
    name: "ui-buttons___ar"
  }, {
    path: "/ar/ui/cards",
    component: _10b3aa4c,
    name: "ui-cards___ar"
  }, {
    path: "/ar/ui/carousel",
    component: _220166f2,
    name: "ui-carousel___ar"
  }, {
    path: "/ar/ui/dropdowns",
    component: _41ebed2a,
    name: "ui-dropdowns___ar"
  }, {
    path: "/ar/ui/general",
    component: _0f6e5111,
    name: "ui-general___ar"
  }, {
    path: "/ar/ui/grid",
    component: _1c20b2ed,
    name: "ui-grid___ar"
  }, {
    path: "/ar/ui/images",
    component: _5735f95f,
    name: "ui-images___ar"
  }, {
    path: "/ar/ui/list-group",
    component: _376437f7,
    name: "ui-list-group___ar"
  }, {
    path: "/ar/ui/modals",
    component: _5714ab4d,
    name: "ui-modals___ar"
  }, {
    path: "/ar/ui/notifications",
    component: _dc1aa75e,
    name: "ui-notifications___ar"
  }, {
    path: "/ar/ui/portlets",
    component: _2953af40,
    name: "ui-portlets___ar"
  }, {
    path: "/ar/ui/progress",
    component: _997f0258,
    name: "ui-progress___ar"
  }, {
    path: "/ar/ui/ribbons",
    component: _d92407f4,
    name: "ui-ribbons___ar"
  }, {
    path: "/ar/ui/spinners",
    component: _5378dfa1,
    name: "ui-spinners___ar"
  }, {
    path: "/ar/ui/tabs-accordions",
    component: _151bfffa,
    name: "ui-tabs-accordions___ar"
  }, {
    path: "/ar/ui/tooltips-popovers",
    component: _e8035f98,
    name: "ui-tooltips-popovers___ar"
  }, {
    path: "/ar/ui/typography",
    component: _1fccf916,
    name: "ui-typography___ar"
  }, {
    path: "/ar/ui/video",
    component: _6db68b64,
    name: "ui-video___ar"
  }, {
    path: "/ar/widgets/data",
    component: _6906038e,
    name: "widgets-data___ar"
  }, {
    path: "/charts/apex/data",
    component: _56c0529b,
    name: "charts-apex-data___en"
  }, {
    path: "/charts/c3/data",
    component: _af9ec966,
    name: "charts-c3-data___en"
  }, {
    path: "/charts/chartist/data",
    component: _2bbb5b11,
    name: "charts-chartist-data___en"
  }, {
    path: "/charts/chartjs/BarChart",
    component: _4e2c589a,
    name: "charts-chartjs-BarChart___en"
  }, {
    path: "/charts/chartjs/DonutChart",
    component: _76cb36aa,
    name: "charts-chartjs-DonutChart___en"
  }, {
    path: "/charts/chartjs/LineChart",
    component: _0a82a8cb,
    name: "charts-chartjs-LineChart___en"
  }, {
    path: "/charts/chartjs/PieChart",
    component: _0d63897e,
    name: "charts-chartjs-PieChart___en"
  }, {
    path: "/charts/chartjs/PolarChart",
    component: _7da897e2,
    name: "charts-chartjs-PolarChart___en"
  }, {
    path: "/charts/chartjs/RadarChart",
    component: _3c2fc147,
    name: "charts-chartjs-RadarChart___en"
  }, {
    path: "/dashboard/analytics/channels",
    component: _19827415,
    name: "dashboard-analytics-channels___en"
  }, {
    path: "/dashboard/analytics/overview",
    component: _790f7d84,
    name: "dashboard-analytics-overview___en"
  }, {
    path: "/dashboard/analytics/social-media",
    component: _30bd4d49,
    name: "dashboard-analytics-social-media___en"
  }, {
    path: "/dashboard/analytics/sources",
    component: _79da79fa,
    name: "dashboard-analytics-sources___en"
  }, {
    path: "/dashboard/analytics/users",
    component: _537d9e13,
    name: "dashboard-analytics-users___en"
  }, {
    path: "/ecommerce/customers/data",
    component: _cec02c06,
    name: "ecommerce-customers-data___en"
  }, {
    path: "/ecommerce/orders/data",
    component: _93ecc17a,
    name: "ecommerce-orders-data___en"
  }, {
    path: "/ecommerce/products/data",
    component: _2c8d0638,
    name: "ecommerce-products-data___en"
  }, {
    path: "/es/account/forgot-password",
    component: _85e838ea,
    name: "account-forgot-password___es"
  }, {
    path: "/es/account/login",
    component: _454ba06f,
    name: "account-login___es"
  }, {
    path: "/es/account/register",
    component: _8bd823e6,
    name: "account-register___es"
  }, {
    path: "/es/apps/calendar",
    component: _2dd131c2,
    name: "apps-calendar___es"
  }, {
    path: "/es/apps/chat",
    component: _eafea776,
    name: "apps-chat___es"
  }, {
    path: "/es/apps/companies",
    component: _5272d348,
    name: "apps-companies___es"
  }, {
    path: "/es/apps/file-manager",
    component: _6ba187a1,
    name: "apps-file-manager___es"
  }, {
    path: "/es/apps/tickets",
    component: _7a224910,
    name: "apps-tickets___es"
  }, {
    path: "/es/auth/confirm-mail",
    component: _71583cc2,
    name: "auth-confirm-mail___es"
  }, {
    path: "/es/auth/confirm-mail-2",
    component: _3c4ee704,
    name: "auth-confirm-mail-2___es"
  }, {
    path: "/es/auth/lock-screen",
    component: _8d062bba,
    name: "auth-lock-screen___es"
  }, {
    path: "/es/auth/lock-screen-2",
    component: _4857de88,
    name: "auth-lock-screen-2___es"
  }, {
    path: "/es/auth/login",
    component: _0b04767e,
    name: "auth-login___es"
  }, {
    path: "/es/auth/login-2",
    component: _562dc023,
    name: "auth-login-2___es"
  }, {
    path: "/es/auth/logout",
    component: _bac93c76,
    name: "auth-logout___es"
  }, {
    path: "/es/auth/logout-2",
    component: _63b6f5aa,
    name: "auth-logout-2___es"
  }, {
    path: "/es/auth/recoverpwd",
    component: _8766c2d8,
    name: "auth-recoverpwd___es"
  }, {
    path: "/es/auth/recoverpwd-2",
    component: _53e78a8e,
    name: "auth-recoverpwd-2___es"
  }, {
    path: "/es/auth/register",
    component: _4aabacc4,
    name: "auth-register___es"
  }, {
    path: "/es/auth/register-2",
    component: _5999a97a,
    name: "auth-register-2___es"
  }, {
    path: "/es/auth/signin-signup",
    component: _2bfc7eb8,
    name: "auth-signin-signup___es"
  }, {
    path: "/es/auth/signin-signup-2",
    component: _1944a1dd,
    name: "auth-signin-signup-2___es"
  }, {
    path: "/es/charts/apex",
    component: _dfba5110,
    name: "charts-apex___es"
  }, {
    path: "/es/charts/c3",
    component: _46a3bbaa,
    name: "charts-c3___es"
  }, {
    path: "/es/charts/chartist",
    component: _127d9a6e,
    name: "charts-chartist___es"
  }, {
    path: "/es/charts/chartjs",
    component: _6165f9f3,
    name: "charts-chartjs___es"
  }, {
    path: "/es/charts/knob",
    component: _d3a1fdc4,
    name: "charts-knob___es"
  }, {
    path: "/es/contacts/list",
    component: _f85d19f8,
    name: "contacts-list___es"
  }, {
    path: "/es/contacts/profile",
    component: _46b8d39a,
    name: "contacts-profile___es"
  }, {
    path: "/es/dashboard/analytics",
    component: _0e13c3dd,
    name: "dashboard-analytics___es"
  }, {
    path: "/es/dashboard/crm",
    component: _7e4a5576,
    name: "dashboard-crm___es"
  }, {
    path: "/es/dashboard/sales",
    component: _540d8b17,
    name: "dashboard-sales___es"
  }, {
    path: "/es/ecommerce/cart",
    component: _19ef8fc6,
    name: "ecommerce-cart___es"
  }, {
    path: "/es/ecommerce/checkout",
    component: _6705ccc3,
    name: "ecommerce-checkout___es"
  }, {
    path: "/es/ecommerce/customers",
    component: _4f0bc34c,
    name: "ecommerce-customers___es"
  }, {
    path: "/es/ecommerce/data-products",
    component: _0bc61456,
    name: "ecommerce-data-products___es"
  }, {
    path: "/es/ecommerce/order-detail",
    component: _cd84f0a6,
    name: "ecommerce-order-detail___es"
  }, {
    path: "/es/ecommerce/orders",
    component: _424b9a20,
    name: "ecommerce-orders___es"
  }, {
    path: "/es/ecommerce/product-create",
    component: _6aea9957,
    name: "ecommerce-product-create___es"
  }, {
    path: "/es/ecommerce/products",
    component: _497a9381,
    name: "ecommerce-products___es"
  }, {
    path: "/es/ecommerce/products-grid",
    component: _191c7462,
    name: "ecommerce-products-grid___es"
  }, {
    path: "/es/ecommerce/sellers",
    component: _b2924e32,
    name: "ecommerce-sellers___es"
  }, {
    path: "/es/email/data-inbox",
    component: _d5b2245a,
    name: "email-data-inbox___es"
  }, {
    path: "/es/email/inbox",
    component: _5f6fc2fd,
    name: "email-inbox___es"
  }, {
    path: "/es/email/sidepanel",
    component: _3a212ef8,
    name: "email-sidepanel___es"
  }, {
    path: "/es/email/templates",
    component: _5a944ab0,
    name: "email-templates___es"
  }, {
    path: "/es/email/toolbar",
    component: _9138249c,
    name: "email-toolbar___es"
  }, {
    path: "/es/extended/rangeslider",
    component: _2506cd42,
    name: "extended-rangeslider___es"
  }, {
    path: "/es/extended/scrollspy",
    component: _4e72c733,
    name: "extended-scrollspy___es"
  }, {
    path: "/es/extended/sweet-alert",
    component: _f1ae86ba,
    name: "extended-sweet-alert___es"
  }, {
    path: "/es/extended/tour",
    component: _bb9d35b8,
    name: "extended-tour___es"
  }, {
    path: "/es/extras/404",
    component: _57bbf872,
    name: "extras-404___es"
  }, {
    path: "/es/extras/404-alt",
    component: _3bde4864,
    name: "extras-404-alt___es"
  }, {
    path: "/es/extras/500",
    component: _e72c54a2,
    name: "extras-500___es"
  }, {
    path: "/es/extras/coming-soon",
    component: _bfc0cafe,
    name: "extras-coming-soon___es"
  }, {
    path: "/es/extras/faqs",
    component: _75926fd3,
    name: "extras-faqs___es"
  }, {
    path: "/es/extras/invoice",
    component: _77e84ee7,
    name: "extras-invoice___es"
  }, {
    path: "/es/extras/lightbox",
    component: _a748d4aa,
    name: "extras-lightbox___es"
  }, {
    path: "/es/extras/maintenance",
    component: _511c0a66,
    name: "extras-maintenance___es"
  }, {
    path: "/es/extras/pricing",
    component: _0828b700,
    name: "extras-pricing___es"
  }, {
    path: "/es/extras/search-results",
    component: _f69fe5f2,
    name: "extras-search-results___es"
  }, {
    path: "/es/extras/sitemap",
    component: _1cddb46f,
    name: "extras-sitemap___es"
  }, {
    path: "/es/extras/starter",
    component: _5a9bcb49,
    name: "extras-starter___es"
  }, {
    path: "/es/extras/timeline",
    component: _1755baf7,
    name: "extras-timeline___es"
  }, {
    path: "/es/forms/advanced",
    component: _6e893bce,
    name: "forms-advanced___es"
  }, {
    path: "/es/forms/elements",
    component: _af9fbbba,
    name: "forms-elements___es"
  }, {
    path: "/es/forms/file-uploads",
    component: _20915d26,
    name: "forms-file-uploads___es"
  }, {
    path: "/es/forms/mask",
    component: _2adee0d0,
    name: "forms-mask___es"
  }, {
    path: "/es/forms/quill",
    component: _6babb4ee,
    name: "forms-quill___es"
  }, {
    path: "/es/forms/validation",
    component: _3eaa38b6,
    name: "forms-validation___es"
  }, {
    path: "/es/forms/wizard",
    component: _227a7cd2,
    name: "forms-wizard___es"
  }, {
    path: "/es/icons/boxicons",
    component: _c662ddf4,
    name: "icons-boxicons___es"
  }, {
    path: "/es/icons/data-fontawesome",
    component: _776363b2,
    name: "icons-data-fontawesome___es"
  }, {
    path: "/es/icons/data-material",
    component: _2b959c0c,
    name: "icons-data-material___es"
  }, {
    path: "/es/icons/data-remix",
    component: _f2db0a1c,
    name: "icons-data-remix___es"
  }, {
    path: "/es/icons/feather",
    component: _c0ff27c8,
    name: "icons-feather___es"
  }, {
    path: "/es/icons/font-awesome",
    component: _a939b988,
    name: "icons-font-awesome___es"
  }, {
    path: "/es/icons/mdi",
    component: _1a13022b,
    name: "icons-mdi___es"
  }, {
    path: "/es/icons/remix",
    component: _66d58c02,
    name: "icons-remix___es"
  }, {
    path: "/es/icons/weather",
    component: _fa9f6a26,
    name: "icons-weather___es"
  }, {
    path: "/es/maps/google",
    component: _aa9e153a,
    name: "maps-google___es"
  }, {
    path: "/es/tables/advanced",
    component: _2034b068,
    name: "tables-advanced___es"
  }, {
    path: "/es/tables/basic",
    component: _4b161ab4,
    name: "tables-basic___es"
  }, {
    path: "/es/task/detail",
    component: _24eb1d69,
    name: "task-detail___es"
  }, {
    path: "/es/task/kanban",
    component: _864c075a,
    name: "task-kanban___es"
  }, {
    path: "/es/task/list",
    component: _23c18736,
    name: "task-list___es"
  }, {
    path: "/es/ui/avatars",
    component: _18748d3a,
    name: "ui-avatars___es"
  }, {
    path: "/es/ui/buttons",
    component: _7339132a,
    name: "ui-buttons___es"
  }, {
    path: "/es/ui/cards",
    component: _10b3aa4c,
    name: "ui-cards___es"
  }, {
    path: "/es/ui/carousel",
    component: _220166f2,
    name: "ui-carousel___es"
  }, {
    path: "/es/ui/dropdowns",
    component: _41ebed2a,
    name: "ui-dropdowns___es"
  }, {
    path: "/es/ui/general",
    component: _0f6e5111,
    name: "ui-general___es"
  }, {
    path: "/es/ui/grid",
    component: _1c20b2ed,
    name: "ui-grid___es"
  }, {
    path: "/es/ui/images",
    component: _5735f95f,
    name: "ui-images___es"
  }, {
    path: "/es/ui/list-group",
    component: _376437f7,
    name: "ui-list-group___es"
  }, {
    path: "/es/ui/modals",
    component: _5714ab4d,
    name: "ui-modals___es"
  }, {
    path: "/es/ui/notifications",
    component: _dc1aa75e,
    name: "ui-notifications___es"
  }, {
    path: "/es/ui/portlets",
    component: _2953af40,
    name: "ui-portlets___es"
  }, {
    path: "/es/ui/progress",
    component: _997f0258,
    name: "ui-progress___es"
  }, {
    path: "/es/ui/ribbons",
    component: _d92407f4,
    name: "ui-ribbons___es"
  }, {
    path: "/es/ui/spinners",
    component: _5378dfa1,
    name: "ui-spinners___es"
  }, {
    path: "/es/ui/tabs-accordions",
    component: _151bfffa,
    name: "ui-tabs-accordions___es"
  }, {
    path: "/es/ui/tooltips-popovers",
    component: _e8035f98,
    name: "ui-tooltips-popovers___es"
  }, {
    path: "/es/ui/typography",
    component: _1fccf916,
    name: "ui-typography___es"
  }, {
    path: "/es/ui/video",
    component: _6db68b64,
    name: "ui-video___es"
  }, {
    path: "/es/widgets/data",
    component: _6906038e,
    name: "widgets-data___es"
  }, {
    path: "/fr/account/forgot-password",
    component: _85e838ea,
    name: "account-forgot-password___fr"
  }, {
    path: "/fr/account/login",
    component: _454ba06f,
    name: "account-login___fr"
  }, {
    path: "/fr/account/register",
    component: _8bd823e6,
    name: "account-register___fr"
  }, {
    path: "/fr/apps/calendar",
    component: _2dd131c2,
    name: "apps-calendar___fr"
  }, {
    path: "/fr/apps/chat",
    component: _eafea776,
    name: "apps-chat___fr"
  }, {
    path: "/fr/apps/companies",
    component: _5272d348,
    name: "apps-companies___fr"
  }, {
    path: "/fr/apps/file-manager",
    component: _6ba187a1,
    name: "apps-file-manager___fr"
  }, {
    path: "/fr/apps/tickets",
    component: _7a224910,
    name: "apps-tickets___fr"
  }, {
    path: "/fr/auth/confirm-mail",
    component: _71583cc2,
    name: "auth-confirm-mail___fr"
  }, {
    path: "/fr/auth/confirm-mail-2",
    component: _3c4ee704,
    name: "auth-confirm-mail-2___fr"
  }, {
    path: "/fr/auth/lock-screen",
    component: _8d062bba,
    name: "auth-lock-screen___fr"
  }, {
    path: "/fr/auth/lock-screen-2",
    component: _4857de88,
    name: "auth-lock-screen-2___fr"
  }, {
    path: "/fr/auth/login",
    component: _0b04767e,
    name: "auth-login___fr"
  }, {
    path: "/fr/auth/login-2",
    component: _562dc023,
    name: "auth-login-2___fr"
  }, {
    path: "/fr/auth/logout",
    component: _bac93c76,
    name: "auth-logout___fr"
  }, {
    path: "/fr/auth/logout-2",
    component: _63b6f5aa,
    name: "auth-logout-2___fr"
  }, {
    path: "/fr/auth/recoverpwd",
    component: _8766c2d8,
    name: "auth-recoverpwd___fr"
  }, {
    path: "/fr/auth/recoverpwd-2",
    component: _53e78a8e,
    name: "auth-recoverpwd-2___fr"
  }, {
    path: "/fr/auth/register",
    component: _4aabacc4,
    name: "auth-register___fr"
  }, {
    path: "/fr/auth/register-2",
    component: _5999a97a,
    name: "auth-register-2___fr"
  }, {
    path: "/fr/auth/signin-signup",
    component: _2bfc7eb8,
    name: "auth-signin-signup___fr"
  }, {
    path: "/fr/auth/signin-signup-2",
    component: _1944a1dd,
    name: "auth-signin-signup-2___fr"
  }, {
    path: "/fr/charts/apex",
    component: _dfba5110,
    name: "charts-apex___fr"
  }, {
    path: "/fr/charts/c3",
    component: _46a3bbaa,
    name: "charts-c3___fr"
  }, {
    path: "/fr/charts/chartist",
    component: _127d9a6e,
    name: "charts-chartist___fr"
  }, {
    path: "/fr/charts/chartjs",
    component: _6165f9f3,
    name: "charts-chartjs___fr"
  }, {
    path: "/fr/charts/knob",
    component: _d3a1fdc4,
    name: "charts-knob___fr"
  }, {
    path: "/fr/contacts/list",
    component: _f85d19f8,
    name: "contacts-list___fr"
  }, {
    path: "/fr/contacts/profile",
    component: _46b8d39a,
    name: "contacts-profile___fr"
  }, {
    path: "/fr/dashboard/analytics",
    component: _0e13c3dd,
    name: "dashboard-analytics___fr"
  }, {
    path: "/fr/dashboard/crm",
    component: _7e4a5576,
    name: "dashboard-crm___fr"
  }, {
    path: "/fr/dashboard/sales",
    component: _540d8b17,
    name: "dashboard-sales___fr"
  }, {
    path: "/fr/ecommerce/cart",
    component: _19ef8fc6,
    name: "ecommerce-cart___fr"
  }, {
    path: "/fr/ecommerce/checkout",
    component: _6705ccc3,
    name: "ecommerce-checkout___fr"
  }, {
    path: "/fr/ecommerce/customers",
    component: _4f0bc34c,
    name: "ecommerce-customers___fr"
  }, {
    path: "/fr/ecommerce/data-products",
    component: _0bc61456,
    name: "ecommerce-data-products___fr"
  }, {
    path: "/fr/ecommerce/order-detail",
    component: _cd84f0a6,
    name: "ecommerce-order-detail___fr"
  }, {
    path: "/fr/ecommerce/orders",
    component: _424b9a20,
    name: "ecommerce-orders___fr"
  }, {
    path: "/fr/ecommerce/product-create",
    component: _6aea9957,
    name: "ecommerce-product-create___fr"
  }, {
    path: "/fr/ecommerce/products",
    component: _497a9381,
    name: "ecommerce-products___fr"
  }, {
    path: "/fr/ecommerce/products-grid",
    component: _191c7462,
    name: "ecommerce-products-grid___fr"
  }, {
    path: "/fr/ecommerce/sellers",
    component: _b2924e32,
    name: "ecommerce-sellers___fr"
  }, {
    path: "/fr/email/data-inbox",
    component: _d5b2245a,
    name: "email-data-inbox___fr"
  }, {
    path: "/fr/email/inbox",
    component: _5f6fc2fd,
    name: "email-inbox___fr"
  }, {
    path: "/fr/email/sidepanel",
    component: _3a212ef8,
    name: "email-sidepanel___fr"
  }, {
    path: "/fr/email/templates",
    component: _5a944ab0,
    name: "email-templates___fr"
  }, {
    path: "/fr/email/toolbar",
    component: _9138249c,
    name: "email-toolbar___fr"
  }, {
    path: "/fr/extended/rangeslider",
    component: _2506cd42,
    name: "extended-rangeslider___fr"
  }, {
    path: "/fr/extended/scrollspy",
    component: _4e72c733,
    name: "extended-scrollspy___fr"
  }, {
    path: "/fr/extended/sweet-alert",
    component: _f1ae86ba,
    name: "extended-sweet-alert___fr"
  }, {
    path: "/fr/extended/tour",
    component: _bb9d35b8,
    name: "extended-tour___fr"
  }, {
    path: "/fr/extras/404",
    component: _57bbf872,
    name: "extras-404___fr"
  }, {
    path: "/fr/extras/404-alt",
    component: _3bde4864,
    name: "extras-404-alt___fr"
  }, {
    path: "/fr/extras/500",
    component: _e72c54a2,
    name: "extras-500___fr"
  }, {
    path: "/fr/extras/coming-soon",
    component: _bfc0cafe,
    name: "extras-coming-soon___fr"
  }, {
    path: "/fr/extras/faqs",
    component: _75926fd3,
    name: "extras-faqs___fr"
  }, {
    path: "/fr/extras/invoice",
    component: _77e84ee7,
    name: "extras-invoice___fr"
  }, {
    path: "/fr/extras/lightbox",
    component: _a748d4aa,
    name: "extras-lightbox___fr"
  }, {
    path: "/fr/extras/maintenance",
    component: _511c0a66,
    name: "extras-maintenance___fr"
  }, {
    path: "/fr/extras/pricing",
    component: _0828b700,
    name: "extras-pricing___fr"
  }, {
    path: "/fr/extras/search-results",
    component: _f69fe5f2,
    name: "extras-search-results___fr"
  }, {
    path: "/fr/extras/sitemap",
    component: _1cddb46f,
    name: "extras-sitemap___fr"
  }, {
    path: "/fr/extras/starter",
    component: _5a9bcb49,
    name: "extras-starter___fr"
  }, {
    path: "/fr/extras/timeline",
    component: _1755baf7,
    name: "extras-timeline___fr"
  }, {
    path: "/fr/forms/advanced",
    component: _6e893bce,
    name: "forms-advanced___fr"
  }, {
    path: "/fr/forms/elements",
    component: _af9fbbba,
    name: "forms-elements___fr"
  }, {
    path: "/fr/forms/file-uploads",
    component: _20915d26,
    name: "forms-file-uploads___fr"
  }, {
    path: "/fr/forms/mask",
    component: _2adee0d0,
    name: "forms-mask___fr"
  }, {
    path: "/fr/forms/quill",
    component: _6babb4ee,
    name: "forms-quill___fr"
  }, {
    path: "/fr/forms/validation",
    component: _3eaa38b6,
    name: "forms-validation___fr"
  }, {
    path: "/fr/forms/wizard",
    component: _227a7cd2,
    name: "forms-wizard___fr"
  }, {
    path: "/fr/icons/boxicons",
    component: _c662ddf4,
    name: "icons-boxicons___fr"
  }, {
    path: "/fr/icons/data-fontawesome",
    component: _776363b2,
    name: "icons-data-fontawesome___fr"
  }, {
    path: "/fr/icons/data-material",
    component: _2b959c0c,
    name: "icons-data-material___fr"
  }, {
    path: "/fr/icons/data-remix",
    component: _f2db0a1c,
    name: "icons-data-remix___fr"
  }, {
    path: "/fr/icons/feather",
    component: _c0ff27c8,
    name: "icons-feather___fr"
  }, {
    path: "/fr/icons/font-awesome",
    component: _a939b988,
    name: "icons-font-awesome___fr"
  }, {
    path: "/fr/icons/mdi",
    component: _1a13022b,
    name: "icons-mdi___fr"
  }, {
    path: "/fr/icons/remix",
    component: _66d58c02,
    name: "icons-remix___fr"
  }, {
    path: "/fr/icons/weather",
    component: _fa9f6a26,
    name: "icons-weather___fr"
  }, {
    path: "/fr/maps/google",
    component: _aa9e153a,
    name: "maps-google___fr"
  }, {
    path: "/fr/tables/advanced",
    component: _2034b068,
    name: "tables-advanced___fr"
  }, {
    path: "/fr/tables/basic",
    component: _4b161ab4,
    name: "tables-basic___fr"
  }, {
    path: "/fr/task/detail",
    component: _24eb1d69,
    name: "task-detail___fr"
  }, {
    path: "/fr/task/kanban",
    component: _864c075a,
    name: "task-kanban___fr"
  }, {
    path: "/fr/task/list",
    component: _23c18736,
    name: "task-list___fr"
  }, {
    path: "/fr/ui/avatars",
    component: _18748d3a,
    name: "ui-avatars___fr"
  }, {
    path: "/fr/ui/buttons",
    component: _7339132a,
    name: "ui-buttons___fr"
  }, {
    path: "/fr/ui/cards",
    component: _10b3aa4c,
    name: "ui-cards___fr"
  }, {
    path: "/fr/ui/carousel",
    component: _220166f2,
    name: "ui-carousel___fr"
  }, {
    path: "/fr/ui/dropdowns",
    component: _41ebed2a,
    name: "ui-dropdowns___fr"
  }, {
    path: "/fr/ui/general",
    component: _0f6e5111,
    name: "ui-general___fr"
  }, {
    path: "/fr/ui/grid",
    component: _1c20b2ed,
    name: "ui-grid___fr"
  }, {
    path: "/fr/ui/images",
    component: _5735f95f,
    name: "ui-images___fr"
  }, {
    path: "/fr/ui/list-group",
    component: _376437f7,
    name: "ui-list-group___fr"
  }, {
    path: "/fr/ui/modals",
    component: _5714ab4d,
    name: "ui-modals___fr"
  }, {
    path: "/fr/ui/notifications",
    component: _dc1aa75e,
    name: "ui-notifications___fr"
  }, {
    path: "/fr/ui/portlets",
    component: _2953af40,
    name: "ui-portlets___fr"
  }, {
    path: "/fr/ui/progress",
    component: _997f0258,
    name: "ui-progress___fr"
  }, {
    path: "/fr/ui/ribbons",
    component: _d92407f4,
    name: "ui-ribbons___fr"
  }, {
    path: "/fr/ui/spinners",
    component: _5378dfa1,
    name: "ui-spinners___fr"
  }, {
    path: "/fr/ui/tabs-accordions",
    component: _151bfffa,
    name: "ui-tabs-accordions___fr"
  }, {
    path: "/fr/ui/tooltips-popovers",
    component: _e8035f98,
    name: "ui-tooltips-popovers___fr"
  }, {
    path: "/fr/ui/typography",
    component: _1fccf916,
    name: "ui-typography___fr"
  }, {
    path: "/fr/ui/video",
    component: _6db68b64,
    name: "ui-video___fr"
  }, {
    path: "/fr/widgets/data",
    component: _6906038e,
    name: "widgets-data___fr"
  }, {
    path: "/tables/advanced/data",
    component: _7e53a78b,
    name: "tables-advanced-data___en"
  }, {
    path: "/task/kanban/data",
    component: _cdbe1b94,
    name: "task-kanban-data___en"
  }, {
    path: "/ar/apps/calendar/data-calendar",
    component: _552ad601,
    name: "apps-calendar-data-calendar___ar"
  }, {
    path: "/ar/apps/chat/data",
    component: _579212b0,
    name: "apps-chat-data___ar"
  }, {
    path: "/ar/apps/companies/data",
    component: _6f630b02,
    name: "apps-companies-data___ar"
  }, {
    path: "/ar/apps/tickets/data",
    component: _3c9f4a33,
    name: "apps-tickets-data___ar"
  }, {
    path: "/ar/charts/apex/data",
    component: _56c0529b,
    name: "charts-apex-data___ar"
  }, {
    path: "/ar/charts/c3/data",
    component: _af9ec966,
    name: "charts-c3-data___ar"
  }, {
    path: "/ar/charts/chartist/data",
    component: _2bbb5b11,
    name: "charts-chartist-data___ar"
  }, {
    path: "/ar/charts/chartjs/BarChart",
    component: _4e2c589a,
    name: "charts-chartjs-BarChart___ar"
  }, {
    path: "/ar/charts/chartjs/DonutChart",
    component: _76cb36aa,
    name: "charts-chartjs-DonutChart___ar"
  }, {
    path: "/ar/charts/chartjs/LineChart",
    component: _0a82a8cb,
    name: "charts-chartjs-LineChart___ar"
  }, {
    path: "/ar/charts/chartjs/PieChart",
    component: _0d63897e,
    name: "charts-chartjs-PieChart___ar"
  }, {
    path: "/ar/charts/chartjs/PolarChart",
    component: _7da897e2,
    name: "charts-chartjs-PolarChart___ar"
  }, {
    path: "/ar/charts/chartjs/RadarChart",
    component: _3c2fc147,
    name: "charts-chartjs-RadarChart___ar"
  }, {
    path: "/ar/dashboard/analytics/channels",
    component: _19827415,
    name: "dashboard-analytics-channels___ar"
  }, {
    path: "/ar/dashboard/analytics/overview",
    component: _790f7d84,
    name: "dashboard-analytics-overview___ar"
  }, {
    path: "/ar/dashboard/analytics/social-media",
    component: _30bd4d49,
    name: "dashboard-analytics-social-media___ar"
  }, {
    path: "/ar/dashboard/analytics/sources",
    component: _79da79fa,
    name: "dashboard-analytics-sources___ar"
  }, {
    path: "/ar/dashboard/analytics/users",
    component: _537d9e13,
    name: "dashboard-analytics-users___ar"
  }, {
    path: "/ar/ecommerce/customers/data",
    component: _cec02c06,
    name: "ecommerce-customers-data___ar"
  }, {
    path: "/ar/ecommerce/orders/data",
    component: _93ecc17a,
    name: "ecommerce-orders-data___ar"
  }, {
    path: "/ar/ecommerce/products/data",
    component: _2c8d0638,
    name: "ecommerce-products-data___ar"
  }, {
    path: "/ar/tables/advanced/data",
    component: _7e53a78b,
    name: "tables-advanced-data___ar"
  }, {
    path: "/ar/task/kanban/data",
    component: _cdbe1b94,
    name: "task-kanban-data___ar"
  }, {
    path: "/es/apps/calendar/data-calendar",
    component: _552ad601,
    name: "apps-calendar-data-calendar___es"
  }, {
    path: "/es/apps/chat/data",
    component: _579212b0,
    name: "apps-chat-data___es"
  }, {
    path: "/es/apps/companies/data",
    component: _6f630b02,
    name: "apps-companies-data___es"
  }, {
    path: "/es/apps/tickets/data",
    component: _3c9f4a33,
    name: "apps-tickets-data___es"
  }, {
    path: "/es/charts/apex/data",
    component: _56c0529b,
    name: "charts-apex-data___es"
  }, {
    path: "/es/charts/c3/data",
    component: _af9ec966,
    name: "charts-c3-data___es"
  }, {
    path: "/es/charts/chartist/data",
    component: _2bbb5b11,
    name: "charts-chartist-data___es"
  }, {
    path: "/es/charts/chartjs/BarChart",
    component: _4e2c589a,
    name: "charts-chartjs-BarChart___es"
  }, {
    path: "/es/charts/chartjs/DonutChart",
    component: _76cb36aa,
    name: "charts-chartjs-DonutChart___es"
  }, {
    path: "/es/charts/chartjs/LineChart",
    component: _0a82a8cb,
    name: "charts-chartjs-LineChart___es"
  }, {
    path: "/es/charts/chartjs/PieChart",
    component: _0d63897e,
    name: "charts-chartjs-PieChart___es"
  }, {
    path: "/es/charts/chartjs/PolarChart",
    component: _7da897e2,
    name: "charts-chartjs-PolarChart___es"
  }, {
    path: "/es/charts/chartjs/RadarChart",
    component: _3c2fc147,
    name: "charts-chartjs-RadarChart___es"
  }, {
    path: "/es/dashboard/analytics/channels",
    component: _19827415,
    name: "dashboard-analytics-channels___es"
  }, {
    path: "/es/dashboard/analytics/overview",
    component: _790f7d84,
    name: "dashboard-analytics-overview___es"
  }, {
    path: "/es/dashboard/analytics/social-media",
    component: _30bd4d49,
    name: "dashboard-analytics-social-media___es"
  }, {
    path: "/es/dashboard/analytics/sources",
    component: _79da79fa,
    name: "dashboard-analytics-sources___es"
  }, {
    path: "/es/dashboard/analytics/users",
    component: _537d9e13,
    name: "dashboard-analytics-users___es"
  }, {
    path: "/es/ecommerce/customers/data",
    component: _cec02c06,
    name: "ecommerce-customers-data___es"
  }, {
    path: "/es/ecommerce/orders/data",
    component: _93ecc17a,
    name: "ecommerce-orders-data___es"
  }, {
    path: "/es/ecommerce/products/data",
    component: _2c8d0638,
    name: "ecommerce-products-data___es"
  }, {
    path: "/es/tables/advanced/data",
    component: _7e53a78b,
    name: "tables-advanced-data___es"
  }, {
    path: "/es/task/kanban/data",
    component: _cdbe1b94,
    name: "task-kanban-data___es"
  }, {
    path: "/fr/apps/calendar/data-calendar",
    component: _552ad601,
    name: "apps-calendar-data-calendar___fr"
  }, {
    path: "/fr/apps/chat/data",
    component: _579212b0,
    name: "apps-chat-data___fr"
  }, {
    path: "/fr/apps/companies/data",
    component: _6f630b02,
    name: "apps-companies-data___fr"
  }, {
    path: "/fr/apps/tickets/data",
    component: _3c9f4a33,
    name: "apps-tickets-data___fr"
  }, {
    path: "/fr/charts/apex/data",
    component: _56c0529b,
    name: "charts-apex-data___fr"
  }, {
    path: "/fr/charts/c3/data",
    component: _af9ec966,
    name: "charts-c3-data___fr"
  }, {
    path: "/fr/charts/chartist/data",
    component: _2bbb5b11,
    name: "charts-chartist-data___fr"
  }, {
    path: "/fr/charts/chartjs/BarChart",
    component: _4e2c589a,
    name: "charts-chartjs-BarChart___fr"
  }, {
    path: "/fr/charts/chartjs/DonutChart",
    component: _76cb36aa,
    name: "charts-chartjs-DonutChart___fr"
  }, {
    path: "/fr/charts/chartjs/LineChart",
    component: _0a82a8cb,
    name: "charts-chartjs-LineChart___fr"
  }, {
    path: "/fr/charts/chartjs/PieChart",
    component: _0d63897e,
    name: "charts-chartjs-PieChart___fr"
  }, {
    path: "/fr/charts/chartjs/PolarChart",
    component: _7da897e2,
    name: "charts-chartjs-PolarChart___fr"
  }, {
    path: "/fr/charts/chartjs/RadarChart",
    component: _3c2fc147,
    name: "charts-chartjs-RadarChart___fr"
  }, {
    path: "/fr/dashboard/analytics/channels",
    component: _19827415,
    name: "dashboard-analytics-channels___fr"
  }, {
    path: "/fr/dashboard/analytics/overview",
    component: _790f7d84,
    name: "dashboard-analytics-overview___fr"
  }, {
    path: "/fr/dashboard/analytics/social-media",
    component: _30bd4d49,
    name: "dashboard-analytics-social-media___fr"
  }, {
    path: "/fr/dashboard/analytics/sources",
    component: _79da79fa,
    name: "dashboard-analytics-sources___fr"
  }, {
    path: "/fr/dashboard/analytics/users",
    component: _537d9e13,
    name: "dashboard-analytics-users___fr"
  }, {
    path: "/fr/ecommerce/customers/data",
    component: _cec02c06,
    name: "ecommerce-customers-data___fr"
  }, {
    path: "/fr/ecommerce/orders/data",
    component: _93ecc17a,
    name: "ecommerce-orders-data___fr"
  }, {
    path: "/fr/ecommerce/products/data",
    component: _2c8d0638,
    name: "ecommerce-products-data___fr"
  }, {
    path: "/fr/tables/advanced/data",
    component: _7e53a78b,
    name: "tables-advanced-data___fr"
  }, {
    path: "/fr/task/kanban/data",
    component: _cdbe1b94,
    name: "task-kanban-data___fr"
  }, {
    path: "/ar/ecommerce/product-detail/:id?",
    component: _3cc62cbe,
    name: "ecommerce-product-detail-id___ar"
  }, {
    path: "/ar/email/reademail/:id?",
    component: _21bef666,
    name: "email-reademail-id___ar"
  }, {
    path: "/es/ecommerce/product-detail/:id?",
    component: _3cc62cbe,
    name: "ecommerce-product-detail-id___es"
  }, {
    path: "/es/email/reademail/:id?",
    component: _21bef666,
    name: "email-reademail-id___es"
  }, {
    path: "/fr/ecommerce/product-detail/:id?",
    component: _3cc62cbe,
    name: "ecommerce-product-detail-id___fr"
  }, {
    path: "/fr/email/reademail/:id?",
    component: _21bef666,
    name: "email-reademail-id___fr"
  }, {
    path: "/ecommerce/product-detail/:id?",
    component: _3cc62cbe,
    name: "ecommerce-product-detail-id___en"
  }, {
    path: "/email/reademail/:id?",
    component: _21bef666,
    name: "email-reademail-id___en"
  }, {
    path: "/",
    component: _7a6dbb4c
  }],

  fallback: false
}

export function createRouter (ssrContext, config) {
  const base = (config._app && config._app.basePath) || routerOptions.base
  const router = new Router({ ...routerOptions, base  })

  // TODO: remove in Nuxt 3
  const originalPush = router.push
  router.push = function push (location, onComplete = emptyFn, onAbort) {
    return originalPush.call(this, location, onComplete, onAbort)
  }

  const resolve = router.resolve.bind(router)
  router.resolve = (to, current, append) => {
    if (typeof to === 'string') {
      to = normalizeURL(to)
    }
    return resolve(to, current, append)
  }

  return router
}
